create database ECOMMERCE
GO
use ECOMMERCE
GO
create table CATEGORIAS
(
ID int identity(1,1) primary key,
CODIGO VARCHAR(8) NOT NULL UNIQUE,
DESCRIPCION VARCHAR(50) NOT NULL,
OBS VARCHAR(200),
ESTADO BIT NOT NULL
)
GO
create table ARTICULOS
(
ID int identity(1,1) primary key,
CODIGO VARCHAR(10) NOT NULL UNIQUE,
DESCRIPCION VARCHAR(50) NOT NULL,
PRECIO float NOT NULL,
TIPO varchar(3) NOT NULL check(tipo = 'ART' OR tipo = 'CON'),
OBS VARCHAR(200),
ESTADO BIT NOT NULL,
ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID) 
)